CREATE TABLE `tournamentEntries` (
	`id` int AUTO_INCREMENT NOT NULL,
	`tournamentId` int NOT NULL,
	`userId` int,
	`isBot` boolean NOT NULL DEFAULT false,
	`botName` varchar(64),
	`botAvatar` varchar(512),
	`botDifficulty` enum('beginner','medium','pro'),
	`chipStack` int NOT NULL DEFAULT 0,
	`status` enum('registered','playing','eliminated','finished') NOT NULL DEFAULT 'registered',
	`finishPosition` int,
	`prizeWon` int NOT NULL DEFAULT 0,
	`eliminatedAt` timestamp,
	`registeredAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `tournamentEntries_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `tournaments` (
	`id` int AUTO_INCREMENT NOT NULL,
	`name` varchar(256) NOT NULL,
	`type` enum('sit_and_go','mtt','freeroll') NOT NULL DEFAULT 'sit_and_go',
	`status` enum('registering','running','paused','completed','cancelled') NOT NULL DEFAULT 'registering',
	`buyIn` int NOT NULL DEFAULT 0,
	`entryFee` int NOT NULL DEFAULT 0,
	`startingChips` int NOT NULL DEFAULT 1500,
	`maxPlayers` int NOT NULL DEFAULT 9,
	`minPlayers` int NOT NULL DEFAULT 2,
	`currentPlayers` int NOT NULL DEFAULT 0,
	`tableSize` enum('2','4','6','9') NOT NULL DEFAULT '6',
	`blindStructure` json NOT NULL,
	`currentBlindLevel` int NOT NULL DEFAULT 0,
	`prizePool` int NOT NULL DEFAULT 0,
	`guaranteedPrize` int NOT NULL DEFAULT 0,
	`payoutStructure` json,
	`botsEnabled` boolean NOT NULL DEFAULT true,
	`botCount` int NOT NULL DEFAULT 3,
	`botDifficulty` enum('beginner','medium','pro','mixed') NOT NULL DEFAULT 'mixed',
	`scheduledStart` timestamp,
	`startedAt` timestamp,
	`endedAt` timestamp,
	`createdBy` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `tournaments_id` PRIMARY KEY(`id`)
);
